### ISSUE TITLE
Feature request: Adiabatic compressible via Y net expansion factors

### ISSUE THREAD

**Issue by non-Jedi** [CalebBell/fluids#15]
Would be a really nice addition to the library. This is equation 1-43 in Crane
TP 410 with accompanying charts on A-23. Cited in the bibliography:

Shapiro, A. H. (1953). *The Dynamics and Thermodynamics of Compressible Fluid
Flow*. John Wiley & Sons.

If you're amenable to inclusion of something like this in the package, I
might take a stab at it myself when I get a chance.

**Comment by CalebBell** [comment]
Hi again Adam,

Sure, absolutely this would be a good addition to fluids. There's quite a bit of compressible gas stuff that could be added to fluids; there are so many cases for it! Compressible flow isn't currently on my to-do list, but I'd be happy to accept a PR and get it out in another release. 

It might be possible to calculate those expansion factors directly in fluids; I'm not sure how they're derived. That would be my preferred approach, rather than implementing a table, if it is possible. Of course, plenty of other places in fluids use lookup tables so it's not a deal breaker.

Sincerely,
Caleb

**Comment by CalebBell** [comment]
Hello,
I am closing this issue because I am somewhat more familiar with compressible flow now. If I am going to put more effort into this topic, it will be a more rigorous approach integrating over a length and using properties from a rigorous thermodynamic model. I would still accept a good PR for this feature, but after 5 years I am not expecting one. 
Sincerely,
Caleb
