### ISSUE TITLE
Errant GPL-3 licensed files in tests directory

### ISSUE THREAD

**Issue by kkremitzki** [CalebBell/fluids#17]
Hi, the files `tests/__init__.py` and `tests/nrlmsise00/__init__.py` are GPL-3 licensed which I figure is a mistake with the rest of the library being MIT licensed.

**Comment by CalebBell** [comment]
Hi Kurt,
Sorry about that! It definitely was not intentional. I've corrected the files, and tagged and pushed version 0.1.72 to pypi with the correction.

Let me know if you find any other issues!

Yeah, I hadn't seen your comment until you submitted the issue - Gitter says I'm signed up for email notifications, but if I get them it's always a long time later :(
