### ISSUE TITLE
vertical torispherical tank, volume at h_max

### ISSUE THREAD

**Issue by anthracitegrey** [CalebBell/fluids#31]
Is it possible that `V_from_h()` of a vertical torispherical tank gets numerically unstable at the very tank top? My guess is `V_vertical_torispherical()`.

My current workaround is not to use `.V_total` and limit queried heights at e.g. `0.9999*h_max`.

Version:
conda-forge/noarch::fluids-0.1.75-py_1

Code to reproduce the problem:

    >>> import fluids as fd
    >>> Tk = fd.TANK(L=3, D=5, horizontal=False, 
    ...     sideA='torispherical', sideA_f=1, sideA_k=0.1,
    ...     sideB='torispherical', sideB_f=1, sideB_k=0.1) #DIN28011
    >>> 
    >>> print(Tk.V_total)
    90.29935171486848
    >>> print(Tk.V_from_h(0.99999*Tk.h_max))
    83.64636099603153
    >>> print(Tk.V_total/2)
    45.14967585743424
    >>> print(Tk.V_from_h(0.50000*Tk.h_max))
    41.82318051716474

**Comment by CalebBell** [comment]
Hi,
Numerical instabilities are always hard to believe until you're debugging them. The issue wasn't quite a numerical stability actually, but a result of floating point precision. The volume of the torispherical head at the start was being calculated at a height of... -2.220446049250313e-16 m, which the formula was doing not nice things at.

This could be fixed by chancing the various volume formulas to return 0 for negative heights. Do you want to prepare a PR?

Sincerely,
Caleb

**Comment by anthracitegrey** [comment]
Hi Caleb, thanks for your rapid answer. I'm afraid I'm not fit enough...
Appreciate your help and thanks for a great library

**Comment by CalebBell** [comment]
Hi,
The change has been made and all the volume formulas have been protected from this error too. They will be in the next release. Thanks for the excellent bug report!

Sincerely,
Caleb

**Comment by CalebBell** [comment]
Heads up the fix is in the latest release on PyPi now!
