### ISSUE TITLE
Pressure Drop for throttle plates

### ISSUE THREAD

**Issue by max3-2** [CalebBell/fluids#62]
Hi,

what would be the recommended method for computing the pressure drop of a simple throttle plate in a pipe? I have flow conditions and `D`, `Do`.

For example, using an orifice correlation at `10lpm`, water approx.
```python
discharge = C_Reader_Harris_Gallagher(16e-3, 8e-3, 1000, 1000 * 1e-6, 10 / 60000 * 1000)
K = discharge_coefficient_to_K(16e-3, 8e-3, discharge)

K
Out[29]: 28.15866270889264
```
this seems pretty high but as I understand is the K-value connected to reoverable and non-recoverable pressure drop. For compressible media, one could compute dP and then use a correlation for the non-recoverable part. I could do the same for incomp. media but I wonder if there's an easier way...

**Comment by CalebBell** [comment]
Hi Max,
You may want to avoid use any of the correlations for specific orifice meter designs for this application. The sharp edges on one side of an orifice plate has a significant impact. Geometry has a significant impact and the equations implemented do not have as input parameters general geometrical parameters, only ones specific to their design. Perhaps a calibration to determine the delta P curve of your orifice yourself is appropriate. Otherwise there is also CFD.
Sincerely,
Caleb
